# Generated by Django 4.1.2 on 2022-10-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YangiliklarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavhasi', models.CharField(max_length=200)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('matni', models.TextField()),
                ('vaqti', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
