# Generated by Django 4.1.2 on 2022-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavhasi', models.CharField(max_length=200)),
                ('tasnifi', models.TextField()),
            ],
        ),
    ]
